# Generated by Django 6.0.3 on 2026-03-08 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pricerecord',
            options={},
        ),
        migrations.RenameField(
            model_name='pricerecord',
            old_name='recorded_date',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='pricerecord',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='pricerecord',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
        migrations.AlterField(
            model_name='pricerecord',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pricerecord',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Cosmetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.hero')),
            ],
        ),
    ]
