# Generated by Django 6.0.3 on 2026-03-11 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_hero_alter_pricerecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetic',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
    ]
